package root

import (
	"encoding/json"
	"html/template"
	"net/http"
	"strconv"
	"strings"

	"github.com/dariubs/altern/app/models"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

type listFormData struct {
	Name            string
	Slug            string
	Subtitle        string
	OwnerID         string
	IsAutoGenerated bool
	IsPrivate       bool
}

type aiPickerItem struct {
	ID       uint   `json:"id"`
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	Subtitle string `json:"subtitle"`
}

func loadAIsJSON(db *gorm.DB) (string, error) {
	var ais []models.AI
	if err := db.Select("id, name, slug, subtitle").Order("name ASC").Find(&ais).Error; err != nil {
		return "[]", err
	}
	items := make([]aiPickerItem, len(ais))
	for i, a := range ais {
		items[i] = aiPickerItem{ID: a.ID, Name: a.Name, Slug: a.Slug, Subtitle: a.Subtitle}
	}
	b, err := json.Marshal(items)
	if err != nil {
		return "[]", err
	}
	return string(b), nil
}

func ListNewForm(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var owners []models.User
		if err := db.Order("username ASC, name ASC").Find(&owners).Error; err != nil {
			c.HTML(http.StatusInternalServerError, "root_list_new.tmpl", gin.H{
				"ActiveNav": "lists",
				"Form":      listFormData{},
				"Error":     "Failed to load owners.",
			})
			return
		}
		aisRaw, _ := loadAIsJSON(db)
		aisJSON := template.JS(aisRaw)
		c.HTML(http.StatusOK, "root_list_new.tmpl", gin.H{
			"ActiveNav": "lists",
			"Form":      listFormData{},
			"Owners":    owners,
			"AIsJSON":   aisJSON,
		})
	}
}

func ListCreate(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		form := listFormData{
			Name:            strings.TrimSpace(c.PostForm("name")),
			Slug:            strings.TrimSpace(c.PostForm("slug")),
			Subtitle:        strings.TrimSpace(c.PostForm("subtitle")),
			OwnerID:         strings.TrimSpace(c.PostForm("owner_id")),
			IsAutoGenerated: c.PostForm("is_auto_generated") == "on",
			IsPrivate:       c.PostForm("is_private") == "on",
		}

		renderErr := func(status int, msg string) {
			var owners []models.User
			_ = db.Order("username ASC, name ASC").Find(&owners).Error
			aisRaw, _ := loadAIsJSON(db)
			aisJSON := template.JS(aisRaw)
			c.HTML(status, "root_list_new.tmpl", gin.H{
				"ActiveNav": "lists",
				"Form":      form,
				"Owners":    owners,
				"AIsJSON":   aisJSON,
				"Error":     msg,
			})
		}

		if form.Name == "" {
			renderErr(http.StatusBadRequest, "Name is required.")
			return
		}
		if form.Slug == "" {
			form.Slug = slugify(form.Name)
		} else {
			form.Slug = slugify(form.Slug)
		}
		if form.Slug == "" {
			renderErr(http.StatusBadRequest, "Slug is required.")
			return
		}
		var existing models.List
		if db.Where("slug = ?", form.Slug).First(&existing).Error == nil {
			renderErr(http.StatusBadRequest, "Slug already in use.")
			return
		}

		list := models.List{
			Name:            form.Name,
			Slug:            form.Slug,
			Subtitle:        form.Subtitle,
			IsAutoGenerated: form.IsAutoGenerated,
			IsPrivate:       form.IsPrivate,
		}
		if form.OwnerID != "" {
			uid, err := strconv.ParseUint(form.OwnerID, 10, 64)
			if err != nil {
				renderErr(http.StatusBadRequest, "Invalid owner.")
				return
			}
			uidU := uint(uid)
			list.UserID = &uidU
		}

		if err := db.Create(&list).Error; err != nil {
			renderErr(http.StatusInternalServerError, "Failed to save list: "+err.Error())
			return
		}

		// Create ListAI records in submitted order.
		aiIDsRaw := strings.TrimSpace(c.PostForm("ai_ids"))
		if aiIDsRaw != "" {
			for sort, part := range strings.Split(aiIDsRaw, ",") {
				part = strings.TrimSpace(part)
				if part == "" {
					continue
				}
				tid, err := strconv.ParseUint(part, 10, 64)
				if err != nil {
					continue
				}
				lt := models.ListAI{ListID: list.ID, AIID: uint(tid), Sort: sort}
				db.Create(&lt)
			}
		}

		c.Redirect(http.StatusFound, "/root/lists")
	}
}
