package root

import (
	"net/http"
	"strconv"
	"strings"

	"github.com/dariubs/altern/app/models"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

type listFormData struct {
	Name            string
	Subtitle        string
	OwnerID         string
	IsAutoGenerated bool
}

func ListNewForm(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var owners []models.User
		if err := db.Order("username ASC, name ASC").Find(&owners).Error; err != nil {
			c.HTML(http.StatusInternalServerError, "list_new.html", gin.H{
				"ActiveNav": "lists",
				"Form":      listFormData{},
				"Error":     "Failed to load owners.",
			})
			return
		}
		c.HTML(http.StatusOK, "list_new.html", gin.H{
			"ActiveNav": "lists",
			"Form":      listFormData{},
			"Owners":    owners,
		})
	}
}

func ListCreate(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		form := listFormData{
			Name:            strings.TrimSpace(c.PostForm("name")),
			Subtitle:        strings.TrimSpace(c.PostForm("subtitle")),
			OwnerID:         strings.TrimSpace(c.PostForm("owner_id")),
			IsAutoGenerated: c.PostForm("is_auto_generated") == "on",
		}

		renderErr := func(status int, msg string) {
			var owners []models.User
			_ = db.Order("username ASC, name ASC").Find(&owners).Error
			c.HTML(status, "list_new.html", gin.H{
				"ActiveNav": "lists",
				"Form":      form,
				"Owners":    owners,
				"Error":     msg,
			})
		}

		if form.Name == "" {
			renderErr(http.StatusBadRequest, "Name is required.")
			return
		}

		list := models.List{
			Name:            form.Name,
			Subtitle:        form.Subtitle,
			IsAutoGenerated: form.IsAutoGenerated,
		}
		if form.OwnerID != "" {
			uid, err := strconv.ParseUint(form.OwnerID, 10, 64)
			if err != nil {
				renderErr(http.StatusBadRequest, "Invalid owner.")
				return
			}
			uidU := uint(uid)
			list.UserID = &uidU
		}

		if err := db.Create(&list).Error; err != nil {
			renderErr(http.StatusInternalServerError, "Failed to save list: "+err.Error())
			return
		}

		c.Redirect(http.StatusFound, "/root/lists")
	}
}
