package root

import (
	"encoding/json"
	"html/template"
	"net/http"
	"strconv"
	"strings"

	"github.com/dariubs/altern/app/models"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

func ListEditForm(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := strconv.ParseUint(c.Param("id"), 10, 64)
		if err != nil {
			c.HTML(http.StatusNotFound, "list_edit.tmpl", gin.H{"ActiveNav": "lists", "Error": "List not found."})
			return
		}

		var list models.List
		if err := db.
			Preload("Items", func(db *gorm.DB) *gorm.DB { return db.Order("sort ASC") }).
			Preload("Items.Tool").
			First(&list, id).Error; err != nil {
			c.HTML(http.StatusNotFound, "list_edit.tmpl", gin.H{"ActiveNav": "lists", "Error": "List not found."})
			return
		}

		var owners []models.User
		_ = db.Order("username ASC, name ASC").Find(&owners).Error

		toolsRaw, _ := loadToolsJSON(db)

		selected := make([]toolPickerItem, 0, len(list.Items))
		for _, item := range list.Items {
			if item.Tool != nil {
				selected = append(selected, toolPickerItem{
					ID:       item.Tool.ID,
					Name:     item.Tool.Name,
					Slug:     item.Tool.Slug,
					Subtitle: item.Tool.Subtitle,
				})
			}
		}
		selRaw, _ := json.Marshal(selected)

		ownerID := ""
		if list.UserID != nil {
			ownerID = strconv.FormatUint(uint64(*list.UserID), 10)
		}

		c.HTML(http.StatusOK, "list_edit.tmpl", gin.H{
			"ActiveNav":    "lists",
			"List":         list,
			"OwnerID":      ownerID,
			"Owners":       owners,
			"ToolsJSON":    template.JS(toolsRaw),
			"SelectedJSON": template.JS(selRaw),
		})
	}
}

func ListUpdate(db *gorm.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := strconv.ParseUint(c.Param("id"), 10, 64)
		if err != nil {
			c.Redirect(http.StatusFound, "/root/lists")
			return
		}

		var list models.List
		if err := db.First(&list, id).Error; err != nil {
			c.Redirect(http.StatusFound, "/root/lists")
			return
		}

		name := strings.TrimSpace(c.PostForm("name"))
		slug := slugify(strings.TrimSpace(c.PostForm("slug")))
		if slug == "" {
			slug = slugify(name)
		}
		subtitle := strings.TrimSpace(c.PostForm("subtitle"))
		ownerID := strings.TrimSpace(c.PostForm("owner_id"))
		isAutoGenerated := c.PostForm("is_auto_generated") == "on"

		renderErr := func(msg string) {
			var owners []models.User
			_ = db.Order("username ASC, name ASC").Find(&owners).Error
			toolsRaw, _ := loadToolsJSON(db)

			// Rebuild selected from current form submission so the picker stays populated.
			var selected []toolPickerItem
			toolIDsRaw := strings.TrimSpace(c.PostForm("tool_ids"))
			if toolIDsRaw != "" {
				for _, part := range strings.Split(toolIDsRaw, ",") {
					part = strings.TrimSpace(part)
					if part == "" {
						continue
					}
					tid, err := strconv.ParseUint(part, 10, 64)
					if err != nil {
						continue
					}
					var t models.Tool
					if db.Select("id, name, slug, subtitle").First(&t, tid).Error == nil {
						selected = append(selected, toolPickerItem{ID: t.ID, Name: t.Name, Slug: t.Slug, Subtitle: t.Subtitle})
					}
				}
			}
			selRaw, _ := json.Marshal(selected)

			c.HTML(http.StatusBadRequest, "list_edit.tmpl", gin.H{
				"ActiveNav":    "lists",
				"List":         list,
				"OwnerID":      ownerID,
				"Owners":       owners,
				"ToolsJSON":    template.JS(toolsRaw),
				"SelectedJSON": template.JS(selRaw),
				"Error":        msg,
			})
		}

		if name == "" {
			renderErr("Name is required.")
			return
		}
		if slug == "" {
			renderErr("Slug is required.")
			return
		}
		var conflict models.List
		if db.Where("slug = ? AND id != ?", slug, list.ID).First(&conflict).Error == nil {
			renderErr("Slug already in use.")
			return
		}

		list.Name = name
		list.Slug = slug
		list.Subtitle = subtitle
		list.IsAutoGenerated = isAutoGenerated
		list.UserID = nil
		if ownerID != "" {
			uid, err := strconv.ParseUint(ownerID, 10, 64)
			if err != nil {
				renderErr("Invalid owner.")
				return
			}
			uidU := uint(uid)
			list.UserID = &uidU
		}

		if err := db.Save(&list).Error; err != nil {
			renderErr("Failed to save list: " + err.Error())
			return
		}

		// Replace all tools.
		db.Where("list_id = ?", list.ID).Delete(&models.ListTool{})
		toolIDsRaw := strings.TrimSpace(c.PostForm("tool_ids"))
		if toolIDsRaw != "" {
			for sort, part := range strings.Split(toolIDsRaw, ",") {
				part = strings.TrimSpace(part)
				if part == "" {
					continue
				}
				tid, err := strconv.ParseUint(part, 10, 64)
				if err != nil {
					continue
				}
				db.Create(&models.ListTool{ListID: list.ID, ToolID: uint(tid), Sort: sort})
			}
		}

		c.Redirect(http.StatusFound, "/root/lists")
	}
}
