package models

import "gorm.io/gorm"

type List struct {
	gorm.Model
	Name            string `gorm:"not null"`
	Slug            string `gorm:"uniqueIndex;not null;default:''"`
	Subtitle        string
	IsAutoGenerated bool `gorm:"default:false"`
	IsPrivate       bool `gorm:"default:false"`

	UserID *uint
	User   *User

	Items []ListAI `gorm:"foreignKey:ListID;constraint:OnDelete:CASCADE"`
}

type ListAI struct {
	ListID uint `gorm:"primaryKey"`
	AIID   uint `gorm:"primaryKey;column:ai_id"`
	Sort   int  `gorm:"default:0;index"`

	List *List
	AI   *AI
}

func (ListAI) TableName() string { return "list_ais" }
