package models

import "gorm.io/gorm"

type List struct {
	gorm.Model
	Name            string `gorm:"not null"`
	Slug            string `gorm:"uniqueIndex;not null;default:''"`
	Subtitle        string
	IsAutoGenerated bool `gorm:"default:false"`

	UserID *uint
	User   *User

	Items []ListTool `gorm:"foreignKey:ListID;constraint:OnDelete:CASCADE"`
}

type ListTool struct {
	ListID uint `gorm:"primaryKey"`
	ToolID uint `gorm:"primaryKey"`
	Sort   int  `gorm:"default:0;index"`

	List *List
	Tool *Tool
}
